### ISSUE TITLE
A bug in data reading script

### ISSUE THREAD

**Issue by RoyJames** [sh01k/MeshRIR#1]
Hi,

I'm trying to take a look at the data, but this matlab script has some problems
https://github.com/sh01k/MeshRIR/blob/30442d60e109560b0ce3dc4d2a9fd1e715802ef8/matfiles/loadIR.m#L16-L23
The thing is the length of `fileList` is larger than the number of microphones because it contains 4 more non-IR files. And it is not guaranteed that when you do `fileList = dir(folderName);` all IR files are sorted first. Therefore, if you use the same index (i), you end up not reading all of the RIRs. And some entries in `fullIR` will be all zeros (on my computer, 997~1000 are zeros if I read from `S1-M3969_mat/`). 

The fix is simple of course. I did a quick fix by doing 
```
    idx = 1;
    for i = 1:size(fileList, 1)
       if strncmp(fileList(i).name, 'ir_', 3)
           %disp(fileList(i).name)
           load(append(folderName, fileList(i).name),'ir');
           allIR(idx, :, :) = ir;
           irIndices(idx) = str2double(extractBetween(fileList(i).name,'ir_','.mat'));
           idx = idx + 1;
       end
    end
```

I'll keep exploring your dataset, and thank you for sharing it.

**Comment by sh01k** [comment]
Thanks for this report! 
I have fixed "matfiles/loadIR.m".
