### ISSUE TITLE
Why is the IR amplitude extremely high?

### ISSUE THREAD

**Issue by sukun1045** [sh01k/MeshRIR#5]
Hi, I download the dataset and try to visualize the IR data for S32-M441. I follow the visualization code but I realize that the IR contains an extremely high peak which looks really weird to me. Shouldn't the IR be bounded by -1 and 1? Is there any bug or it is the noise from the data? I attach a screenshot and here the srcIdx and micIdx are both 0.
![image](https://user-images.githubusercontent.com/22249737/164138188-c0ae7b73-a981-469f-8018-2b4439cf1898.png)

**Comment by sh01k** [comment]
We measured IRs using swept-sine signals. These signals are amplified by loudspeaker and microphone amplifiers. Then, the measured swept-sine signals are converted into IRs. 
That is the reason why the peak of the IR is larger than 1.

**Comment by sukun1045** [comment]
Ok. But suppose I want to save it as a wav file. What would be the reasonable process to do that? Is it ok to normalize it between -1 to 1?

**Comment by sh01k** [comment]
You can normalize the data by the maximum absolute value of IRs. 
1) Find the maximum absolute value from IRs you want to analyze. 
2) Divide all IRs by the value found in 1). You can change the range of value by multiplying arbitrary constant.

**Comment by sukun1045** [comment]
thanks.
