### ISSUE TITLE
Is the Mic and Speaker time synchronized? 

### ISSUE THREAD

**Issue by ZitongLan** [sh01k/MeshRIR#6]
Thanks for your dataset! I am currently looking into your dataset and have the following question: I check the data sample using ir_view.ipynb. It seems that the largest response come at nearly time 0.2s. But the distance between mic and speaker is less than 20m. It only takes 20/340 = 0.05s for sound wave to travel this distance. Does the speaker send pluse at time 0?

**Comment by sh01k** [comment]
This is due to the processing delay of the audio interface and measurement software. We didn't compensate for this so the initial response was delayed more than the physical delay.

**Comment by sh01k** [comment]
I believe so because the relative delays between mics are reasonable.

**Comment by ZitongLan** [comment]
Thanks for your answer,  I do have one more question. From another issue you answered:
"We measured IRs using swept-sine signals. These signals are amplified by loudspeaker and microphone amplifiers. Then, the measured swept-sine signals are converted into IRs. "

Do you get the IRs using FMCW signal, which is the chirp signals? If so, after that, what specific solutions you have employed to get the impulse response from the output (microphone) and input (emitter) data?

**Comment by sh01k** [comment]
We used a swept-sine signal (a.k.a. time-stretched pulse/chirp signal) for measurement. The recorded swept-sine signal is convoluted with the inverse swept-sine signal to get the IR. See the following paper:
https://doi.org/10.1121/1.412224

**Comment by ZitongLan** [comment]
Thank you for the answers!
